### ISSUE TITLE
import error: Open Multi-Processing?

### ISSUE THREAD

**Issue by kcfriend** [CloudCompare/CloudComPy#191]
**When I import only cloudcompy, the program runs normally. However, when I add import open3d after it, the following error occurs:**
(myenvpy310) zxc@zxcdeMacBook-Pro CloudComPy310 % python /Users/zxc/Documents/Projects/0731reconstruct/zxcTest/cclabel_main.py
JsonRPCPlugin::JsonRPCPlugin
OMP: Error #179: Function pthread_mutex_init failed:
OMP: System error #22: Invalid argument
zsh: abort      python /Users/zxc/Documents/Projects/0731reconstruct/zxcTest/cclabel_main.py

**If I swap the order of the imports, i.e., import open3d first and then cloudcompy, I get the following error:
Traceback (most recent call last):**
  File "/Users/zxc/Documents/Projects/0731reconstruct/zxcTest/cclabel_main.py", line 3, in <module>
    import ccLabel
  File "/Users/zxc/Documents/Projects/0731reconstruct/zxcTest/ccLabel.py", line 3, in <module>
    import cloudComPy as cc 
  File "/Users/zxc/Downloads/CloudComPy310/cloudComPy/__init__.py", line 34, in <module>
    from _cloudComPy import *
ImportError: dlopen(/Users/zxc/Downloads/CloudComPy310/CloudCompare/CloudCompare.app/Contents/Frameworks/_cloudComPy.cpython-310-darwin.so, 0x0002): Symbol not found: _opj_decoder_set_strict_mode
  Referenced from: <FEB21DEB-64FB-3E0E-8F0C-43DE160181B8> /Users/zxc/Downloads/CloudComPy310/CloudCompare/CloudCompare.app/Contents/Frameworks/libgdal.32.dylib
  Expected in:     <B9EB1A55-3DA8-3BDF-8575-7A3B20B0BF2F> /opt/miniconda3/envs/myenvpy310/lib/libopenjp2.2.4.0.dylib

I use the .zsh to activate these, could you help me figure out the soulution?

**Comment by prascle** [comment]
Hello, sorry for the late reply, I didn't have my mac to test.

I can't reproduce your problem. I work with the conda CloudComPy310 environment described in the [documentation](https://github.com/CloudCompare/CloudComPy/blob/master/doc/UseMacOSCondaBinary.md). I add open3d to the conda environment with `conda install open3d`. In this environment, I can import cloudComPy and open3d in any order and execute cloudComPy and open3d scripts (I use `. bin/condaCloud.zsh activate CloudComPy310` to load the conda environment and set the PYTHONPATH for cloudComPy).

However, the implementation of openMP is tricky on macOS, it is used by cloudComPy and probably also by open3d and I guess it works because conda provides a consistent configuration for both packages.

Best regards,
Paul
